model_name: "bart-large"

dataset_dir: /home/andrew/CS4248_project/dataset/

train_dataset:
  filename_ls_path: data_split/train.txt
  csv_file: train.csv

val_dataset:
  filename_ls_path: data_split/val.txt
  csv_file: val.csv

half_precision: False

save_pred_path: